global:
  resolve_timeout: 5m
  smtp_smarthost: 'localhost:25'
  smtp_from: 'Alertmanager <vagrant@promotheus1.localdomain>'
  smtp_require_tls: false
 
 # The smarthost and SMTP sender used for mail notifications.
 #   smtp_smarthost: 'smtp.xxx.it:587'
 #     smtp_from: 'Alertmanager <alertmanager@example.org>'
 #
 #     Next you need to set 2 environment variables containing your user / passsword
 #
 #     SMTP_AUTH_USERNAME=xxx@xxx.it
 #     SMTP_AUTH_PASSWORD=xxx
 #


route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  #receiver: 'web.hook'
  receiver: 'admins'

receivers:
#- name: 'web.hook'
#  webhook_configs:
#  - url: 'http://127.0.0.1:5001/'
#
  - name: 'admins'
    email_configs:
      - to: 'Vagrant <vagrant@promotheus1.localdomain>'
     # - send_resolved: true
     # - from: 'Alertmanager <vagrant@promotheus1.localdomain>'
     # - smarthost: 'loalhost:25'
    #auth_username: 'ADDDDDDDDDDDDDDDDDDQ'
    #auth_password: 'ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDq'
    #slack_configs:


inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
